### PR TITLE
Updating azo_vine model to fix the compartments issue. 

### PR DESCRIPTION
**Pull request by JamesPino**
Differences between the original and updated model can be viewed in fix_compartment_diff.html. The updated model has 3 compartments, transport reactions, and increased total biomass production.

My thought is to use the README.md for each model to track changes, keep code that modifies the models, then keep a series of model xml files (then we can track A -> B using script1.py, which adds N to the model). Then we can run memote diff on them to compare them. The diff report is also in the repo, so we can see the differences. Then the history of the model can be viewed and tracked.

Any thoughts? I added everyone to review for now for discussion.

### CODE REVIEW

**Comment by mcnaughtonadm** [comment]
Just to make sure I understand it right. We would generate a new model xml (call it AV_2.xml) but also retain the older model xmls (AV_1.xml and AV_0.xml)? Or would we only be saving the original and the most updated model to compare (only AV_2.xml and AV_0.xml)? 

Depending on the amount of changes we make, we may end up saving a lot of old models if we just incremented the version number of the model and saved it with the rest.

**Comment by djinnome** [comment]
As far as I understood @JamesPino 's suggestion,  git keeps track of the versions, so the procedure would be this:
1.  check out the oldest version AV.xml (version 0)
2.  run the AV0_to_1.py script on it to generate AV_1.xml 
3.  Check out AV.xml (version 1). 
4. Compare it with AV_1.xml to ensure they are the same.
5  run AV1_to_2.py script to generate AV_2.xml
5. Check out AV.xml (version 2)
6. Compare it with AV_2.xml to ensure they are the same.
etc.

**Comment by djinnome** [comment]
Or alternately we could just run:

```python
git checkout v0 AV.yml
python AV_0_to_1.py AV.yml | AV_1_to_2.py > AV_2.xml
git checkout AV.yml
diff AV.yml AV_2.yml
```

**Comment by djinnome** [comment]
We might even add a flag to the conversion code so that it spits out a summary of the changes that it would make without actually making them.  This way, the README gets automatically appended.

**Comment by JamesPino** [comment]
After some thought, I was wondering if we could just start with the original model, then keep each update to a function (update_1() with a description). Then we write out a AV.xml (or SE, RT) by running all the updates. This keeps only 2 model files (starting and ending), and updates are tracked in the function calls.

```
import starting_model

with starting_model as updated_model:
   # update compartment names
    update_1()
    # adds inchi_ids to metabolites
    update_2()
   # etc etc etc
   cobra.write(updated_model, 'AV.xml')
```

The readme would have more details about each update, so only short comments to help us recall needed in the update functions.

Memote will track the changes for each update, so my original thought of keeping versions was bad. If we wanted to compare specific version, we could always write out a model after N update functions calls too, so we can keep things around without explicitly tracking.

**Comment by djinnome** [comment]
Hi James, This seems like a rational way to proceed.  We keep a named original model around, but all subsequent versions are tracked by Memote/git, not through named instances.

**Review by vladpetyuk — APPROVED** [review]

**Pull request merged**
